spring:
  main:
    banner-mode: "off"
  datasource:
    url: "jdbc:mysql://170.231.179.246:3306/ATPS"
    username: ""
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  thymeleaf:
    prefix: classpath:/templates/
    cache: true
  resources:
    static-locations: classpath:/static/

logging:
  config: config/log4j2.xml
  level:
    spring: warn
    ar: info

management:
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN

